// Generated by CoffeeScript 1.7.1
var any, clump, defineProperty, every, exec, findBy, first, isNumber, last, listCoffeeArrStr, listString, normalize, sortBy, unique, wrapAt, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __slice = [].slice;

_ref = require('./utils'), every = _ref.every, any = _ref.any, unique = _ref.unique, isNumber = _ref.isNumber;

_ref1 = require('./listString'), listCoffeeArrStr = _ref1.listCoffeeArrStr, listString = _ref1.listString;

last = function(me) {
  return me[me.length - 1];
};

first = function(me) {
  return me[0];
};

sortBy = function(me, property) {
  if (every(me, isNumber)) {
    return me.sort(function(a, b) {
      return a[property] - b[property];
    });
  } else {
    return me.sort(function(a, b) {
      return a[property].localeCompare(b[property]);
    });
  }
};

findBy = function(me, properties) {
  var item, key, match, val, _i, _len;
  if (properties == null) {
    properties = {};
  }
  for (_i = 0, _len = me.length; _i < _len; _i++) {
    item = me[_i];
    match = true;
    for (key in properties) {
      if (!__hasProp.call(properties, key)) continue;
      val = properties[key];
      if (!(item[key] !== val)) {
        continue;
      }
      match = false;
      break;
    }
    if (match) {
      return item;
    }
  }
  return null;
};

clump = function(me, n) {
  var i, j, _i, _ref2, _results;
  if (n == null) {
    n = 2;
  }
  _results = [];
  for (j = _i = 0, _ref2 = me.length; n > 0 ? _i < _ref2 : _i > _ref2; j = _i += n) {
    _results.push((function() {
      var _j, _results1;
      _results1 = [];
      for (i = _j = 0; 0 <= n ? _j < n : _j > n; i = 0 <= n ? ++_j : --_j) {
        if ((i + j) < me.length) {
          _results1.push(me[i + j]);
        }
      }
      return _results1;
    })());
  }
  return _results;
};

normalize = function(me) {
  var i, num, sum, _i, _j, _len, _len1, _results;
  sum = 0;
  for (_i = 0, _len = me.length; _i < _len; _i++) {
    num = me[_i];
    sum += num;
  }
  _results = [];
  for (i = _j = 0, _len1 = me.length; _j < _len1; i = ++_j) {
    num = me[i];
    _results.push(me[i] /= sum);
  }
  return _results;
};

wrapAt = function(me, index) {
  return me[index % me.length];
};

defineProperty = Object.defineProperty;

if (defineProperty == null) {
  defineProperty = function(object, name, descriptor) {
    if (descriptor.get != null) {
      return object.__defineGetter__(name, descriptor.get);
    } else if (descriptor.value != null) {
      return object[name] = descriptor.value;
    }
  };
}

module.exports = {
  last: last,
  listString: listString,
  listCoffeeArrStr: listCoffeeArrStr,
  sortBy: sortBy,
  findBy: findBy,
  unique: unique,
  clump: clump,
  normalize: normalize,
  any: any,
  wrapAt: wrapAt,
  pollute: function() {
    var fn, name, _ref2, _results;
    _ref2 = module.exports;
    _results = [];
    for (name in _ref2) {
      if (!__hasProp.call(_ref2, name)) continue;
      fn = _ref2[name];
      if (name !== 'pollute') {
        _results.push((function(fn) {
          var descriptor;
          descriptor = {
            enumerable: false,
            value: function() {
              var args;
              args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
              return fn.apply(null, [this].concat(args));
            }
          };
          if (Array.prototype[name] == null) {
            return defineProperty(Array.prototype, name, descriptor);
          }
        })(fn));
      }
    }
    return _results;
  }
};

if (require.main === module) {
  exec = require('child_process').exec;
  exec('cake build', function(error, stdout, stderr) {
    return console.log({
      error: error,
      stdout: stdout,
      stderr: stderr
    });
  });
  module.exports.pollute();
  console.log([1, 2, 3].listString());
  console.log([1, 2, 3].normalize());
  console.log([1, 2, 3].last());
  console.log(['apple', 'Apple'].unique(function(item) {
    return item.toUpperCase();
  }));
  console.log([
    {
      name: "Fred",
      ID: 1
    }, {
      name: "Joe"
    }
  ].findBy({
    ID: 1
  }));
}
