// Generated by CoffeeScript 1.7.1
var any, clump, defineProperty, every, exec, first, last, listString, normalize, sortBy, unique, _ref,
  __slice = [].slice;

_ref = require('./utils'), every = _ref.every, any = _ref.any, unique = _ref.unique;

listString = require('./listString');

last = function(me) {
  return me[me.length - 1];
};

first = function(me) {
  return me[0];
};

sortBy = function(me, property) {
  return me.sort(function(a, b) {
    return a[property] - b[property];
  });
};

clump = function(me, n) {
  var i, j, _i, _ref1, _results;
  if (n == null) {
    n = 2;
  }
  _results = [];
  for (j = _i = 0, _ref1 = me.length; n > 0 ? _i < _ref1 : _i > _ref1; j = _i += n) {
    _results.push((function() {
      var _j, _results1;
      _results1 = [];
      for (i = _j = 0; 0 <= n ? _j < n : _j > n; i = 0 <= n ? ++_j : --_j) {
        if ((i + j) < me.length) {
          _results1.push(me[i + j]);
        }
      }
      return _results1;
    })());
  }
  return _results;
};

normalize = function(me) {
  var i, num, sum, _i, _j, _len, _len1, _results;
  sum = 0;
  for (_i = 0, _len = me.length; _i < _len; _i++) {
    num = me[_i];
    sum += num;
  }
  _results = [];
  for (i = _j = 0, _len1 = me.length; _j < _len1; i = ++_j) {
    num = me[i];
    _results.push(me[i] /= sum);
  }
  return _results;
};

defineProperty = Object.defineProperty;

if (defineProperty == null) {
  defineProperty = function(object, name, descriptor) {
    if (descriptor.get != null) {
      return object.__defineGetter__(name, descriptor.get);
    } else if (descriptor.value != null) {
      return object[name] = descriptor.value;
    }
  };
}

module.exports = {
  last: last,
  listString: listString,
  sortBy: sortBy,
  unique: unique,
  clump: clump,
  normalize: normalize,
  any: any,
  pollute: function() {
    var fn, name, _ref1, _results;
    _ref1 = module.exports;
    _results = [];
    for (name in _ref1) {
      fn = _ref1[name];
      if (name !== 'pollute') {
        _results.push((function(fn) {
          var descriptor;
          descriptor = {
            enumerable: false,
            value: function() {
              var args;
              args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
              return fn.apply(null, [this].concat(args));
            }
          };
          if (Array.prototype[name] == null) {
            return defineProperty(Array.prototype, name, descriptor);
          }
        })(fn));
      }
    }
    return _results;
  }
};

if (require.main === module) {
  exec = require('child_process').exec;
  exec('cake build', function(error, stdout, stderr) {
    return console.log({
      error: error,
      stdout: stdout,
      stderr: stderr
    });
  });
  module.exports.pollute();
  console.log([1, 2, 3].listString());
  console.log([1, 2, 3].normalize());
  console.log([1, 2, 3].last());
  console.log(['apple', 'Apple'].unique(function(item) {
    return item.toUpperCase();
  }));
}
