// Generated by CoffeeScript 1.9.1
var Articles, any, consolidateAlphaRanges, consolidateRanges, every, exec, isInt, listCoffeeArrStr, listString, ref, unique;

ref = require('./utils'), every = ref.every, any = ref.any, unique = ref.unique, isInt = ref.isInt;

Articles = require('articles');

listString = function(me, andor, article, comma) {
  var a, andOrProvided, arr, complex, delimiter, isRange, item;
  if (comma == null) {
    comma = ', ';
  }
  isRange = andor == null;
  if (andor == null) {
    andor = 'and';
  }
  andOrProvided = (andor != null ? andor.length : void 0) > 0;
  isRange = every(me, isInt);
  if (isRange) {
    arr = consolidateRanges((function() {
      var j, len, results;
      results = [];
      for (j = 0, len = me.length; j < len; j++) {
        a = me[j];
        results.push(parseInt(a));
      }
      return results;
    })());
  } else {
    isRange = every(me, function(item) {
      return /^[a-z]$/i.test(item);
    });
    if (isRange) {
      arr = consolidateAlphaRanges(me);
    }
  }
  if (me.length > 2) {
    if (isRange) {
      if (arr.length > 2) {
        delimiter = comma;
      }
    } else {
      complex = any(me, function(item) {
        return /,/.test(item);
      });
      delimiter = complex ? '; ' : comma;
    }
  }
  if (delimiter == null) {
    delimiter = andOrProvided ? andor : '';
    if (/^[\w\/]+$/i.test(delimiter)) {
      delimiter = " " + delimiter + " ";
    }
  }
  if (arr == null) {
    arr = me.slice(0);
  }
  if (/^an?$/.test(article)) {
    arr = (function() {
      var j, len, results;
      results = [];
      for (j = 0, len = arr.length; j < len; j++) {
        item = arr[j];
        results.push(Articles.articlize(item));
      }
      return results;
    })();
  } else if ((article != null ? article.length : void 0) > 0) {
    arr = (function() {
      var j, len, results;
      results = [];
      for (j = 0, len = arr.length; j < len; j++) {
        item = arr[j];
        results.push(article + " " + item);
      }
      return results;
    })();
  }
  if (andOrProvided && (arr.length > 2)) {
    arr.push(andor + " " + (arr.pop()));
  }
  return arr.join(delimiter);
};

listCoffeeArrStr = function(me) {
  var arr;
  arr = consolidateRanges(me, '..');
  if (arr.length > 1 && any(arr, function(item) {
    return /\d\.\.\d/.test(item);
  })) {
    return "[].concat.call([" + (arr.join('], [')) + "])";
  } else {
    return "[" + (arr.join(', ')) + "]";
  }
};

consolidateRanges = function(inputArray, delimiter) {
  var arr, end, i, j, k, len, len1, num, rangeBegs, rangeEnds, results, start;
  if (delimiter == null) {
    delimiter = '–';
  }
  arr = unique(inputArray).sort(function(a, b) {
    return a - b;
  });
  rangeEnds = [];
  rangeBegs = [];
  for (i = j = 0, len = arr.length; j < len; i = ++j) {
    num = arr[i];
    if (num !== arr[i - 1] + 1) {
      rangeBegs.push(num);
    }
    if (num !== arr[i + 1] - 1) {
      rangeEnds.push(num);
    }
  }
  results = [];
  for (i = k = 0, len1 = rangeBegs.length; k < len1; i = ++k) {
    start = rangeBegs[i];
    end = rangeEnds[i];
    if (start === end) {
      results.push(start);
    } else {
      results.push("" + start + delimiter + end);
    }
  }
  return results;
};

consolidateAlphaRanges = function(inputArray, delimiter) {
  var arr, end, i, j, k, len, len1, ltr, rangeBegs, rangeEnds, ref1, ref2, results, start;
  if (delimiter == null) {
    delimiter = '–';
  }
  arr = unique(inputArray).sort();
  rangeEnds = [];
  rangeBegs = [];
  for (i = j = 0, len = arr.length; j < len; i = ++j) {
    ltr = arr[i];
    if (ltr.charCodeAt() !== ((ref1 = arr[i - 1]) != null ? ref1.charCodeAt() : void 0) + 1) {
      rangeBegs.push(ltr);
    }
    if (ltr.charCodeAt() !== ((ref2 = arr[i + 1]) != null ? ref2.charCodeAt() : void 0) - 1) {
      rangeEnds.push(ltr);
    }
  }
  results = [];
  for (i = k = 0, len1 = rangeBegs.length; k < len1; i = ++k) {
    start = rangeBegs[i];
    end = rangeEnds[i];
    if (start === end) {
      results.push(start);
    } else {
      results.push("" + start + delimiter + end);
    }
  }
  return results;
};

module.exports = {
  listString: listString,
  listCoffeeArrStr: listCoffeeArrStr
};

if (require.main === module) {
  exec = require('child_process').exec;
  exec('cake build', function(error, stdout, stderr) {
    return console.log({
      error: error,
      stdout: stdout,
      stderr: stderr
    });
  });
  console.log(listCoffeeArrStr([1, 2, 3, 4]));
  console.log(listCoffeeArrStr([1, 2, 3, 4, 11, 21, 22, 23]));
  console.log(listCoffeeArrStr([1, 3, 5]));
}
