// Generated by CoffeeScript 1.7.1
module.exports = {
  every: function(arr, testFn) {
    var i, item, _i, _len;
    for (i = _i = 0, _len = arr.length; _i < _len; i = ++_i) {
      item = arr[i];
      if (!testFn(item, i)) {
        return false;
      }
    }
    return true;
  },
  any: function(arr, testFn) {
    var i, item, _i, _len;
    for (i = _i = 0, _len = arr.length; _i < _len; i = ++_i) {
      item = arr[i];
      if (testFn(item, i)) {
        return true;
      }
    }
    return false;
  },
  unique: function(me, compareFn) {
    var key, out, val, value, _i, _j, _len, _len1, _results;
    out = {};
    if (compareFn != null) {
      for (_i = 0, _len = me.length; _i < _len; _i++) {
        val = me[_i];
        val = compareFn(val);
        out[val] = val;
      }
    } else {
      for (_j = 0, _len1 = me.length; _j < _len1; _j++) {
        val = me[_j];
        out[val] = val;
      }
    }
    _results = [];
    for (key in out) {
      value = out[key];
      _results.push(value);
    }
    return _results;
  },
  isNumber: function(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  },
  isInt: function(value) {
    return !isNaN(parseInt(value, 10)) && (parseFloat(value, 10) === parseInt(value, 10));
  }
};
